services:
  apache:
    depends_on:
      - shell
      - user
    container_name: inventory-apache
    image: inventory-apache
    build:
      dockerfile: Dockerfile
      context: ./apache
    ports:
      - "80:80"
    extra_hosts:
      - host.docker.internal:host-gateway
  shell:
    stdin_open: true
    container_name: inventory-shell
    image: inventory-shell
    build:
      dockerfile: ./projects/shell/Dockerfile
      context: .
    ports:
      - "4200:80"
  user:
    stdin_open: true
    container_name: inventory-user
    image: inventory-user
    build:
      dockerfile: ./projects/user/frontend/Dockerfile
      context: .
    ports:
      - "4210:80"
