worker_processes 1;
error_log stderr ${LOG_LEVEL};
pid /var/run/nginx.pid;

events { worker_connections 1024; }

http {

    server {
        listen 80;
        server_name localhost.com;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        http2 on;
        server_name localhost.com;
        charset utf-8;

        ssl_certificate /etc/ssl/certs/localhost.crt;
        ssl_certificate_key /etc/ssl/certs/localhost.key;

        # Recommended SSL settings (more on this below)
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers on;

        # Root URL redirect to shell service
        # rewrite ^/$ /shell/ permanent;
        # location = / {
        #     proxy_pass ${SHELL_HOST}:${SHELL_PORT}/;
        # }

        # User service routing
        location /user {
            proxy_pass ${USER_HOST}:${USER_PORT};
        }

        # Shell service routing for all other requests
        location / {
            proxy_pass ${SHELL_HOST}:${SHELL_PORT};
        }
    }
}
