worker_processes 1;
error_log stderr ${LOG_LEVEL};
pid /var/run/nginx.pid;

events { worker_connections 1024; }

http {

    server {
        listen 80;
        server_name localhost.com;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        http2 on;
        server_name localhost.com;
        charset utf-8;

        ssl_certificate /etc/ssl/certs/localhost.crt;
        ssl_certificate_key /etc/ssl/certs/localhost.key;

        # Recommended SSL settings (more on this below)
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers on;

        # Include for headers (if you have one)
        # include /etc/nginx/conf.d/headers.conf;

        # Equivalent of ProxyPreserveHost on
        # proxy_set_header Host $host;
        # proxy_set_header X-Real-IP $remote_addr;
        # proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        # proxy_set_header X-Forwarded-Proto $scheme;

        # Redirect root to /shell/
        # rewrite ^/$ /shell/ permanent;
        location = / {
            return 301 /shell/;
        }

        location /shell/ {
            proxy_pass ${SHELL_HOST}:${SHELL_PORT}/shell/;
        }

        location /user/ {
            proxy_pass ${USER_HOST}:${USER_PORT}/user/;
        }
    }
}
